name: Build and Push PackerCMD Images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - master
    paths:
      - packercmd/**

jobs:
  push:
    name: "packercmd:${{ matrix.distro }}"  # Ganti jadi 'packercmd'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Penting biar bisa push ke GHCR pakai GITHUB_TOKEN

    strategy:
      fail-fast: false
      matrix:
        distro:
          - debian
          - dotnet
          - proton

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ../packercmd  # Update path ke 'packercmd'
          file: ../packercmd/${{ matrix.distro }}/Dockerfile  # Update path ke 'packercmd'
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/packercmd:${{ matrix.distro }}
            ${{ github.repository_owner == 'josplay1' && format('ghcr.io/josplay1/packercmd:{0}', matrix.distro) || '' }}
