jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .  # Gunakan repositori root sebagai konteks
          file: ./${{ matrix.distro }}/Dockerfile  # Ganti path sesuai dengan folder distro di root
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/packercmd:${{ matrix.distro }}
